# Setup
title:               JunkMechanism
tagline:             'Curve-Fitting My Experiences'
description:         'Groove and grease'
avatar:              /images/mechanic.svg
url:                 https://junkmechanic.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ankur Khanna
  email:             khanna89ankur@gmail.com

github:
  repo:              https://github.com/junkmechanic/junkmechanic.github.io

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
