# Setup
title:               JunkMechanism
tagline:             'Curve-Fitting My Experiences'
description:         'Groove and grease'
url:                 https://junkmechanic.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ankur Khanna
  email:             khanna89ankur@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
